GET http://localhost:8080/v1/isdp-auth/isdp/saas/dic/_queryWithTree/12
Content-Type: application/json

{}

###
POST http://localhost:8080/v1/isdp-auth/isdp/saas/dic/_insert
Content-Type: application/json

{
  "code": "dic001",
  "name": "设备字典",
  "seq": 5,
  "tenant_id": "saas"
}

###
